import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";


export default function Consignado() {
    

  return (
    
    <div>
      <Head>
        <title>Espaço Digital Financeiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
        />
      </Head>

      <Header></Header>
      <main>

      </main>
      <Footer></Footer>
    </div>
  );
}
