import Head from "next/head";
import styles from "../../styles/Home.module.css";
import Header from "../components/Header";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import Form from "../components/Form";
import CardEmprestimo from "../components/CardEmprestimo";
import CardCartao from "../components/CardCartao";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Espaço Digital Financeiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main>
        <section className={styles.container__section}>
          <div className={styles.corte}>
            <p className={styles.h1}>Precisando de dinheiro?</p>
            <p className={styles.h3__word}>
              Fazemos emprestimo para BPC-LOAS, Aposentados, Pensionistas,
              Servidores Públicos e FGTS
            </p>
            <p className={styles.h3}>
              Liberação rápida, 100% digital no conforto da sua casa
            </p>
            <section className={styles.section2}>
              <CardEmprestimo />
            </section>
            <section className={styles.section2}>
              <h2 className={styles.mg__cartao}>Antecipação saque FGTS</h2>
              <CardCartao />
            </section>
          </div>
          <div className={styles.corte2}>
            <img className={styles.img} />
          </div>
        </section>
      </main>
      <Contact />
      <div className={styles.form__now}>
        <div className={styles.fixed}>
          <h3 className={styles.simulacao__title}>Simulação Emprestimo</h3>
          <p className={styles.simulacao__words}>
            Simule e contrate sem sair de casa para BPC-LOAS, Aposentados,
            Pensionistas, Servidores Públicos e FGTS
          </p>
          <p className={styles.simulacao__words}>
            Seguimos as normas LGPD, tornando os dados cadastrados seguros e
            protegidos, tendo o objetivo unicamente para identificação e contato
            ao cliente
          </p>
          <p className={styles.simulacao__words}>
            Ao confirmar o envio dos dados, o cliente está totalmente informado
            para qual afinidade os dados foram solicitados
          </p>
        </div>
        <div className={styles.form__center}>
          <div className={styles.form__center2}>
            <Form></Form>
          </div>
        </div>
      </div>
      <Footer></Footer>
      
    </div>
    
  );
  
}

