import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import styles from "../../styles/sobrenos.module.css";

export default function Instituicao() {
  return (
    <div>
      <Head>
        <title>Espaço Digital Financeiro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
        />
      </Head>

      <Header></Header>

      <div className={styles.test}>
        <section class={styles.aboutUs}>
          <h2 className={styles.margin}>Sobre Nós</h2>
          <p className={styles.p}>
            Nossa missão é proporcionar soluções financeiras que atendam às
            necessidades dos nossos clientes, oferecendo opções de crédito para
            que possam alcançar seus objetivos com segurança e confiança.
          </p>

          <h2 className={styles.margin2}>Nossos Valores</h2>
          <div class={styles.valuesContainer}>
            <div class={styles.valueCard}>
              <div className={styles.Img} alt="Integridade" />
              <h3>Integridade</h3>
              <p className={styles.p}>
                Atuamos com ética, transparência e responsabilidade em todas as
                nossas ações.
              </p>
            </div>

            <div class={styles.valueCard}>
              <div className={styles.Img2} alt="Inovação" />
              <h3>Inovação</h3>
              <p className={styles.p}>
                Buscamos constantemente soluções criativas e tecnológicas para
                atender às necessidades dos nossos clientes.
              </p>
            </div>

            <div class={styles.valueCard}>
              <div className={styles.Img3} alt="Comprometimento" />
              <h3>Comprometimento</h3>
              <p className={styles.p}>
                Estamos empenhados em oferecer um serviço de qualidade e
                transparente.
              </p>
            </div>
          </div>

          <h2 className={styles.margin2}>Junte-se a nós</h2>
          <p class={styles.smallText}>
            Se você está em busca de uma empresa confiável, experiente e
            comprometida em oferecer as melhores soluções financeiras para você,
            venha fazer parte da nossa família de clientes. Estamos prontos para
            atender às suas necessidades e ajudá-lo a alcançar seus objetivos
            financeiros.
          </p>
          <a href="./" class={styles.btn}>
            Conhecer produtos
          </a>
          <div className={styles.mapContainer}>
          <h3 className={styles.mapInfo}>Localização</h3>

          <div className={styles.mainmapOverlay}>
            <iframe
              className={styles.map}
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3755.497692239!2d-47.96839712577554!3d-19.733998532233155!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94bad14f4002850f%3A0xe8b82b5c3365e32!2sEspa%C3%A7o%20Digital%20Financeiro!5e0!3m2!1spt-BR!2sbr!4v1689787924277!5m2!1spt-BR!2sbr"
              allowFullScreen=""
              loading="lazy"
            ></iframe>
            
            <p className={styles.mapOverlay}>
              Horário de funcionamento
              <br />
              Segunda a Sexta: 9:30 - 18:00
              <br />
              Sábado: 9:30 - 13:00
            </p>
          </div>
        </div>
        </section>
        
      </div>
      <Footer></Footer>
    </div>
  );
}
